pipelines:
  - pipeline_id: msfragger_unipept
    modality: DDA
    search_engine: dda_msfragger_philosopher
    protein_inference: null
    taxon_inference: unipept_lca

  - pipeline_id: comet_unipept
    modality: DDA
    search_engine: dda_comet
    protein_inference: null
    taxon_inference: unipept_lca

  - pipeline_id: msgfplus_unipept
    modality: DDA
    search_engine: dda_msgfplus
    protein_inference: null
    taxon_inference: unipept_lca

  - pipeline_id: msfragger_proteoclade
    modality: DDA
    search_engine: dda_msfragger_philosopher
    protein_inference: null
    taxon_inference: proteoclade

  - pipeline_id: comet_proteoclade
    modality: DDA
    search_engine: dda_comet
    protein_inference: null
    taxon_inference: proteoclade

  - pipeline_id: msgfplus_proteoclade
    modality: DDA
    search_engine: dda_msgfplus
    protein_inference: null
    taxon_inference: proteoclade

  - pipeline_id: msfragger_prophet_unipept
    modality: DDA
    search_engine: dda_msfragger_philosopher
    protein_inference: philosopher_proteinprophet
    taxon_inference: unipept_lca
